# Generated by Django 4.1.7 on 2023-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('ram', 'ram'), ('storage', 'storage')], max_length=100),
        ),
    ]
