# Generated by Django 4.2.2 on 2023-07-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_offerproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproducts',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
