# Generated by Django 4.2.2 on 2023-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_offerproducts_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproducts',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
