# Generated by Django 4.2.2 on 2023-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sate', models.CharField(blank=True, max_length=250)),
                ('area', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
