# Generated by Django 4.2.2 on 2023-07-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deliveryaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='sate',
            new_name='state',
        ),
    ]
