# Generated by Django 4.1.7 on 2023-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
